import { asc, eq } from "drizzle-orm";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { requirePermission } from "@/app/authorization";
import { getDb } from "@/db";
import { goals } from "@/db/schema";

const validTypes=new Set(["sales","approved_proposals","received","margin"]);
export async function GET(){if(!await getChatGPTUser())return Response.json({error:"Sessão não autenticada."},{status:401});try{return Response.json({goals:await getDb().select().from(goals).orderBy(asc(goals.startsAt))});}catch{return Response.json({error:"Não foi possível carregar as metas."},{status:503});}}
export async function POST(request:Request){const denied=await requirePermission("crm");if(denied)return denied;if(!await getChatGPTUser())return Response.json({error:"Sessão não autenticada."},{status:401});try{const p=await request.json() as Record<string,unknown>,name=String(p.name??"").trim(),type=String(p.type??"sales"),target=Number(p.target),startsAt=String(p.startsAt??""),endsAt=String(p.endsAt??"");if(!name||!validTypes.has(type)||!Number.isFinite(target)||target<=0||!/^\d{4}-\d{2}-\d{2}$/.test(startsAt)||!/^\d{4}-\d{2}-\d{2}$/.test(endsAt)||endsAt<startsAt)return Response.json({error:"Revise o nome, o valor e o período da meta."},{status:400});const [goal]=await getDb().insert(goals).values({name,type,target,startsAt,endsAt}).returning();return Response.json({goal},{status:201});}catch{return Response.json({error:"Não foi possível cadastrar a meta."},{status:500});}}
export async function PATCH(request:Request){const denied=await requirePermission("crm");if(denied)return denied;if(!await getChatGPTUser())return Response.json({error:"Sessão não autenticada."},{status:401});try{const p=await request.json() as Record<string,unknown>,id=Number(p.id),name=String(p.name??"").trim(),type=String(p.type??"sales"),target=Number(p.target),startsAt=String(p.startsAt??""),endsAt=String(p.endsAt??"");if(!id||!name||!validTypes.has(type)||!Number.isFinite(target)||target<=0||endsAt<startsAt)return Response.json({error:"Revise os dados da meta."},{status:400});const [goal]=await getDb().update(goals).set({name,type,target,startsAt,endsAt,active:p.active!==false,updatedAt:new Date().toISOString()}).where(eq(goals.id,id)).returning();return goal?Response.json({goal}):Response.json({error:"Meta não encontrada."},{status:404});}catch{return Response.json({error:"Não foi possível atualizar a meta."},{status:500});}}
export async function DELETE(request:Request){const denied=await requirePermission("crm");if(denied)return denied;if(!await getChatGPTUser())return Response.json({error:"Sessão não autenticada."},{status:401});try{const id=Number(new URL(request.url).searchParams.get("id"));const [goal]=await getDb().delete(goals).where(eq(goals.id,id)).returning();return goal?Response.json({success:true}):Response.json({error:"Meta não encontrada."},{status:404});}catch{return Response.json({error:"Não foi possível excluir a meta."},{status:500});}}
