CREATE TABLE `service_field_executions` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `assignment_id` integer NOT NULL UNIQUE, `service_call_id` integer NOT NULL, `technician_id` integer NOT NULL, `status` text DEFAULT 'assigned' NOT NULL, `invited_at` text, `accepted_at` text, `declined_at` text, `expected_arrival_at` text, `departed_at` text, `arrived_at` text, `checked_in_at` text, `started_at` text, `finished_at` text, `checked_out_at` text, `closed_at` text, `check_in_latitude` real, `check_in_longitude` real, `check_out_latitude` real, `check_out_longitude` real, `decline_reason` text, `return_reason` text, `technician_report` text, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, `updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (`assignment_id`) REFERENCES `service_call_technicians`(`id`) ON DELETE cascade, FOREIGN KEY (`service_call_id`) REFERENCES `service_calls`(`id`) ON DELETE cascade, FOREIGN KEY (`technician_id`) REFERENCES `service_technicians`(`id`));--> statement-breakpoint
CREATE INDEX `idx_service_field_execution_call` ON `service_field_executions` (`service_call_id`,`status`);--> statement-breakpoint
CREATE INDEX `idx_service_field_execution_tech` ON `service_field_executions` (`technician_id`,`status`);--> statement-breakpoint
CREATE TABLE `service_field_events` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `execution_id` integer NOT NULL, `service_call_id` integer NOT NULL, `technician_id` integer NOT NULL, `event_type` text NOT NULL, `occurred_at` text NOT NULL, `latitude` real, `longitude` real, `note` text, `performed_by` text NOT NULL, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (`execution_id`) REFERENCES `service_field_executions`(`id`) ON DELETE cascade);--> statement-breakpoint
CREATE INDEX `idx_service_field_events_execution` ON `service_field_events` (`execution_id`,`occurred_at`);--> statement-breakpoint
CREATE TABLE `service_field_evidences` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `execution_id` integer NOT NULL, `service_call_id` integer NOT NULL, `file_id` integer, `evidence_type` text DEFAULT 'photo' NOT NULL, `title` text NOT NULL, `description` text, `url` text, `captured_at` text NOT NULL, `uploaded_by` text NOT NULL, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (`execution_id`) REFERENCES `service_field_executions`(`id`) ON DELETE cascade);--> statement-breakpoint
CREATE INDEX `idx_service_field_evidences_execution` ON `service_field_evidences` (`execution_id`,`created_at`);--> statement-breakpoint
CREATE TABLE `service_field_expense_links` (`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, `execution_id` integer NOT NULL, `expense_id` integer NOT NULL UNIQUE, `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY (`execution_id`) REFERENCES `service_field_executions`(`id`) ON DELETE cascade);--> statement-breakpoint
CREATE INDEX `idx_service_field_expense_execution` ON `service_field_expense_links` (`execution_id`);
