import { sql } from "drizzle-orm";
import { getDb } from "@/db";
import { ensureServiceTechnicianTables } from "@/app/service-technician-runtime";

export async function ensureServiceFieldExecutionTables() {
  await ensureServiceTechnicianTables();
  const db = getDb();
  await db.run(sql.raw(`CREATE TABLE IF NOT EXISTS service_field_executions (id INTEGER PRIMARY KEY AUTOINCREMENT, assignment_id INTEGER NOT NULL UNIQUE, service_call_id INTEGER NOT NULL, technician_id INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'assigned', invited_at TEXT, accepted_at TEXT, declined_at TEXT, expected_arrival_at TEXT, departed_at TEXT, arrived_at TEXT, checked_in_at TEXT, started_at TEXT, finished_at TEXT, checked_out_at TEXT, closed_at TEXT, check_in_latitude REAL, check_in_longitude REAL, check_out_latitude REAL, check_out_longitude REAL, decline_reason TEXT, return_reason TEXT, technician_report TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (assignment_id) REFERENCES service_call_technicians(id) ON DELETE CASCADE, FOREIGN KEY (service_call_id) REFERENCES service_calls(id) ON DELETE CASCADE, FOREIGN KEY (technician_id) REFERENCES service_technicians(id))`));
  await db.run(sql.raw(`CREATE INDEX IF NOT EXISTS idx_service_field_execution_call ON service_field_executions(service_call_id,status)`));
  await db.run(sql.raw(`CREATE INDEX IF NOT EXISTS idx_service_field_execution_tech ON service_field_executions(technician_id,status)`));
  await db.run(sql.raw(`CREATE TABLE IF NOT EXISTS service_field_events (id INTEGER PRIMARY KEY AUTOINCREMENT, execution_id INTEGER NOT NULL, service_call_id INTEGER NOT NULL, technician_id INTEGER NOT NULL, event_type TEXT NOT NULL, occurred_at TEXT NOT NULL, latitude REAL, longitude REAL, note TEXT, performed_by TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (execution_id) REFERENCES service_field_executions(id) ON DELETE CASCADE, FOREIGN KEY (service_call_id) REFERENCES service_calls(id) ON DELETE CASCADE, FOREIGN KEY (technician_id) REFERENCES service_technicians(id))`));
  await db.run(sql.raw(`CREATE INDEX IF NOT EXISTS idx_service_field_events_execution ON service_field_events(execution_id,occurred_at)`));
  await db.run(sql.raw(`CREATE TABLE IF NOT EXISTS service_field_evidences (id INTEGER PRIMARY KEY AUTOINCREMENT, execution_id INTEGER NOT NULL, service_call_id INTEGER NOT NULL, file_id INTEGER, evidence_type TEXT NOT NULL DEFAULT 'photo', title TEXT NOT NULL, description TEXT, url TEXT, captured_at TEXT NOT NULL, uploaded_by TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (execution_id) REFERENCES service_field_executions(id) ON DELETE CASCADE, FOREIGN KEY (service_call_id) REFERENCES service_calls(id) ON DELETE CASCADE, FOREIGN KEY (file_id) REFERENCES service_call_files(id) ON DELETE SET NULL)`));
  await db.run(sql.raw(`CREATE INDEX IF NOT EXISTS idx_service_field_evidences_execution ON service_field_evidences(execution_id,created_at)`));
  await db.run(sql.raw(`CREATE TABLE IF NOT EXISTS service_field_expense_links (id INTEGER PRIMARY KEY AUTOINCREMENT, execution_id INTEGER NOT NULL, expense_id INTEGER NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (execution_id) REFERENCES service_field_executions(id) ON DELETE CASCADE, FOREIGN KEY (expense_id) REFERENCES service_call_expenses(id) ON DELETE CASCADE)`));
  await db.run(sql.raw(`CREATE INDEX IF NOT EXISTS idx_service_field_expense_execution ON service_field_expense_links(execution_id)`));
}
