"use client";
import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";

type Call = { id:number; number:string; companyName:string; location:string|null };
type Assignment = { id:number; technicianName:string; assignmentStatus:string };
type Event = { id:number; eventType:string; occurredAt:string; note:string|null };
type Execution = { id:number; assignmentId:number; technicianName:string; status:string; expectedArrivalAt:string|null; events:Event[]; evidences:Array<{id:number;title:string;description:string|null;url:string|null}>; expenses:Array<{id:number;category:string;description:string;amount:number}> };
const labels:Record<string,string>={assigned:"Atribuído",invited:"Acionado",accepted:"Aceito",declined:"Recusado",en_route:"Em deslocamento",arrived:"Chegou ao cliente",checked_in:"Check-in",in_progress:"Em atendimento",finished:"Atendimento finalizado",return_required:"Retorno necessário",checked_out:"Check-out",closed:"Encerrado",cancelled:"Cancelado"};
const next:Record<string,Array<[string,string]>>={assigned:[["invited","Acionar técnico"]],invited:[["accepted","Registrar aceite"],["declined","Registrar recusa"]],accepted:[["en_route","Iniciar deslocamento"]],en_route:[["arrived","Registrar chegada"]],arrived:[["checked_in","Fazer check-in"]],checked_in:[["in_progress","Iniciar atendimento"]],in_progress:[["finished","Finalizar atendimento"],["return_required","Solicitar retorno"]],return_required:[["accepted","Confirmar nova visita"]],finished:[["checked_out","Fazer check-out"],["closed","Encerrar OS técnica"]],checked_out:[["closed","Encerrar OS técnica"]]};
const dt=(v:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(v));
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);
function callNumber(el:HTMLElement|null){return el?.textContent?.match(/TDK-\d{6}/)?.[0]??null;}

export function ServiceFieldExecutionDashboard(){
 const [target,setTarget]=useState<HTMLElement|null>(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState("");
 const [calls,setCalls]=useState<Call[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[executions,setExecutions]=useState<Execution[]>([]),[selected,setSelected]=useState<number|null>(null);
 const [note,setNote]=useState(""),[eta,setEta]=useState(""),[evidence,setEvidence]=useState({title:"",description:"",url:""}),[expense,setExpense]=useState({category:"deslocamento",description:"",amount:""});
 useEffect(()=>{const locate=()=>setTarget(document.querySelector<HTMLElement>(".service-call-sheet .opportunity-sheet-body"));locate();const o=new MutationObserver(locate);o.observe(document.body,{childList:true,subtree:true});fetch("/api/service-calls",{cache:"no-store"}).then(r=>r.json()).then(d=>setCalls(d.serviceCalls??[])).catch(()=>{});return()=>o.disconnect()},[]);
 const call=useMemo(()=>calls.find(c=>c.number===callNumber(target))??null,[calls,target]);
 async function refresh(){if(!call)return;setLoading(true);setMessage("");try{const [a,e]=await Promise.all([fetch(`/api/service-call-technicians?serviceCallId=${call.id}`,{cache:"no-store"}),fetch(`/api/service-field-execution?serviceCallId=${call.id}`,{cache:"no-store"})]);const ad=await a.json(),ed=await e.json();if(!a.ok||!e.ok)throw new Error(ad.error??ed.error);setAssignments(ad.assignments??[]);setExecutions(ed.executions??[]);setSelected((v)=>v??ed.executions?.[0]?.id??null)}catch(err){setMessage(err instanceof Error?err.message:"Falha ao carregar jornada.")}finally{setLoading(false)}}
 async function api(body:Record<string,unknown>){setLoading(true);setMessage("");try{const r=await fetch("/api/service-field-execution",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error??"Falha na operação.");if(d.executions)setExecutions(d.executions);setNote("");return d}catch(err){setMessage(err instanceof Error?err.message:"Falha na operação.");throw err}finally{setLoading(false)}}
 async function launch(){setOpen(true);await refresh()}
 async function create(assignmentId:number){const d=await api({action:"create",assignmentId});setSelected(d.execution.id);await refresh()}
 async function position(){return new Promise<{latitude?:number;longitude?:number}>(resolve=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude}),()=>resolve({}),{enableHighAccuracy:true,timeout:8000}):resolve({}))}
 async function transition(status:string){if(!selected)return;const needsReason=["declined","return_required"].includes(status);if(needsReason&&!note.trim()){setMessage("Informe o motivo antes de continuar.");return}const geo=["checked_in","checked_out"].includes(status)?await position():{};await api({action:"transition",executionId:selected,status,note,expectedArrivalAt:eta||undefined,...geo})}
 const current=executions.find(e=>e.id===selected)??null;
 return <>{target&&call?createPortal(<div className="field-sheet-action"><button type="button" onClick={()=>void launch()}>JORNADA DO TÉCNICO</button></div>,target):null}
 {open&&createPortal(<div className="field-overlay" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="field-modal"><header><div><small>FIELD SERVICE · EXECUÇÃO</small><h2>Jornada do técnico</h2><p>{call?.number} · {call?.companyName} · {call?.location||"sem local"}</p></div><button onClick={()=>setOpen(false)}>×</button></header>{message&&<div className="field-message">{message}</div>}
 <div className="field-body"><aside><h3>Técnicos da OS</h3>{assignments.map(a=>{const ex=executions.find(e=>e.assignmentId===a.id);return <button className={selected===ex?.id?"active":""} key={a.id} onClick={()=>ex?setSelected(ex.id):void create(a.id)}><b>{a.technicianName}</b><span>{ex?labels[ex.status]??ex.status:"Iniciar jornada"}</span></button>})}{!assignments.length&&<p>Nenhum técnico atribuído.</p>}</aside><main>{current?<><div className="field-status"><small>ETAPA ATUAL</small><h3>{labels[current.status]??current.status}</h3>{current.expectedArrivalAt&&<p>Previsão de chegada: {dt(current.expectedArrivalAt)}</p>}</div>
 <div className="field-actions">{current.status==="invited"&&<label>Previsão de chegada<input type="datetime-local" value={eta} onChange={e=>setEta(e.target.value)}/></label>}<label>Observação / relatório<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Obrigatório para recusa e retorno"/></label><div>{(next[current.status]??[]).map(([s,l])=><button key={s} disabled={loading} className={s==="declined"||s==="return_required"?"warning":"primary"} onClick={()=>void transition(s)}>{l}</button>)}</div></div>
 <section className="field-card"><h4>Linha do tempo de campo</h4>{current.events.length?current.events.map(e=><div className="field-event" key={e.id}><i/><span><b>{labels[e.eventType]??e.eventType}</b><small>{dt(e.occurredAt)}{e.note?` · ${e.note}`:""}</small></span></div>):<p>Acione o técnico para iniciar.</p>}</section>
 <div className="field-columns"><section className="field-card"><h4>Evidências e fotos</h4><input placeholder="Título" value={evidence.title} onChange={e=>setEvidence(v=>({...v,title:e.target.value}))}/><input placeholder="Link da foto/arquivo (opcional)" value={evidence.url} onChange={e=>setEvidence(v=>({...v,url:e.target.value}))}/><textarea placeholder="Descrição" value={evidence.description} onChange={e=>setEvidence(v=>({...v,description:e.target.value}))}/><button disabled={!evidence.title||loading} onClick={()=>void api({action:"evidence",executionId:current.id,...evidence}).then(()=>setEvidence({title:"",description:"",url:""}))}>Adicionar evidência</button>{current.evidences.map(e=><p key={e.id}><b>{e.url?<a href={e.url} target="_blank" rel="noreferrer">{e.title}</a>:e.title}</b><br/><small>{e.description}</small></p>)}</section>
 <section className="field-card"><h4>Despesas do atendimento</h4><select value={expense.category} onChange={e=>setExpense(v=>({...v,category:e.target.value}))}><option value="deslocamento">Deslocamento</option><option value="alimentacao">Alimentação</option><option value="estacionamento">Estacionamento</option><option value="pedagio">Pedágio</option><option value="outros">Outros</option></select><input placeholder="Descrição" value={expense.description} onChange={e=>setExpense(v=>({...v,description:e.target.value}))}/><input type="number" min="0" step="0.01" placeholder="Valor" value={expense.amount} onChange={e=>setExpense(v=>({...v,amount:e.target.value}))}/><button disabled={!expense.description||!expense.amount||loading} onClick={()=>void api({action:"expense",executionId:current.id,...expense}).then(()=>setExpense({category:"deslocamento",description:"",amount:""}))}>Lançar despesa</button>{current.expenses.map(e=><p key={e.id}><b>{e.description}</b> · {money(e.amount)}</p>)}</section></div></>:<div className="field-empty">Selecione um técnico e inicie a jornada operacional.</div>}</main></div></section></div>,document.body)}</>;
}
