import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const users=sqliteTable("users",{id:integer("id").primaryKey({autoIncrement:true}),externalId:text("external_id").notNull().unique(),email:text("email").notNull().unique(),name:text("name").notNull(),role:text("role").notNull().default("seller"),managerId:integer("manager_id"),active:integer("active",{mode:"boolean"}).notNull().default(true),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const companies=sqliteTable("companies",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),document:text("document"),segment:text("segment"),ownerId:integer("owner_id").references(()=>users.id),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const contacts=sqliteTable("contacts",{id:integer("id").primaryKey({autoIncrement:true}),companyId:integer("company_id").notNull().references(()=>companies.id),name:text("name").notNull(),role:text("role"),email:text("email"),phone:text("phone"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const opportunities=sqliteTable("opportunities",{id:integer("id").primaryKey({autoIncrement:true}),title:text("title").notNull(),companyId:integer("company_id").references(()=>companies.id),companyName:text("company_name").notNull(),value:real("value").notNull().default(0),stage:text("stage").notNull().default("novo"),probability:integer("probability").notNull().default(10),temperature:text("temperature").notNull().default("warm"),ownerId:integer("owner_id").references(()=>users.id),ownerName:text("owner_name").notNull(),expectedCloseAt:text("expected_close_at"),lostReason:text("lost_reason"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const activities=sqliteTable("activities",{id:integer("id").primaryKey({autoIncrement:true}),opportunityId:integer("opportunity_id").notNull().references(()=>opportunities.id),userId:integer("user_id").references(()=>users.id),type:text("type").notNull(),description:text("description").notNull(),dueAt:text("due_at"),completedAt:text("completed_at"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const proposals=sqliteTable("proposals",{id:integer("id").primaryKey({autoIncrement:true}),opportunityId:integer("opportunity_id").notNull().references(()=>opportunities.id),number:text("number").notNull().unique(),status:text("status").notNull().default("rascunho"),validUntil:text("valid_until"),discount:real("discount").notNull().default(0),subtotal:real("subtotal").notNull().default(0),total:real("total").notNull().default(0),notes:text("notes"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const proposalItems=sqliteTable("proposal_items",{id:integer("id").primaryKey({autoIncrement:true}),proposalId:integer("proposal_id").notNull().references(()=>proposals.id),category:text("category").notNull(),description:text("description").notNull(),quantity:real("quantity").notNull().default(1),unitPrice:real("unit_price").notNull().default(0),total:real("total").notNull().default(0)});
