import { env } from "cloudflare:workers";
import { asc, eq } from "drizzle-orm";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { requirePermission } from "@/app/authorization";
import { getDb } from "@/db";
import { serviceCallFiles } from "@/db/schema";

export async function GET(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:"Sessão não autenticada."},{status:401});try{const id=Number(new URL(request.url).searchParams.get("id"));if(id){const [file]=await getDb().select().from(serviceCallFiles).where(eq(serviceCallFiles.id,id)).limit(1);if(!file)return Response.json({error:"Foto não encontrada."},{status:404});const object=await env.BUCKET.get(file.storageKey);if(!object)return Response.json({error:"Conteúdo da foto não encontrado."},{status:404});return new Response(object.body,{headers:{"Content-Type":file.contentType,"Content-Disposition":`inline; filename*=UTF-8''${encodeURIComponent(file.name)}`}});}return Response.json({files:await getDb().select().from(serviceCallFiles).orderBy(asc(serviceCallFiles.createdAt))});}catch{return Response.json({error:"Não foi possível carregar as evidências."},{status:503});}}
export async function POST(request:Request){const denied=await requirePermission("sales");if(denied)return denied;const user=await getChatGPTUser();if(!user)return Response.json({error:"Sessão não autenticada."},{status:401});try{const data=await request.formData(),serviceCallId=Number(data.get("serviceCallId")),file=data.get("file");if(!serviceCallId||!(file instanceof File)||!file.size||!file.type.startsWith("image/"))return Response.json({error:"Selecione uma foto válida."},{status:400});if(file.size>10*1024*1024)return Response.json({error:"A foto deve ter no máximo 10 MB."},{status:400});const safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-").slice(-120)||"evidencia.jpg",storageKey=`service-calls/${serviceCallId}/${crypto.randomUUID()}-${safeName}`;await env.BUCKET.put(storageKey,file.stream(),{httpMetadata:{contentType:file.type}});const [created]=await getDb().insert(serviceCallFiles).values({serviceCallId,name:file.name.slice(0,180),storageKey,contentType:file.type,size:file.size,uploadedBy:user.displayName}).returning();return Response.json({file:created},{status:201});}catch{return Response.json({error:"Não foi possível enviar a foto."},{status:500});}}
export async function DELETE(request:Request){const denied=await requirePermission("sales");if(denied)return denied;try{const id=Number(new URL(request.url).searchParams.get("id"));const [file]=await getDb().select().from(serviceCallFiles).where(eq(serviceCallFiles.id,id)).limit(1);if(!file)return Response.json({error:"Foto não encontrada."},{status:404});await env.BUCKET.delete(file.storageKey);await getDb().delete(serviceCallFiles).where(eq(serviceCallFiles.id,id));return Response.json({ok:true});}catch{return Response.json({error:"Não foi possível excluir a foto."},{status:500});}}
