import { env } from "cloudflare:workers";
import { asc, eq } from "drizzle-orm";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { requirePermission } from "@/app/authorization";
import { getDb } from "@/db";
import { projectFiles } from "@/db/schema";

export async function GET(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:"Sessão não autenticada."},{status:401});try{const id=Number(new URL(request.url).searchParams.get("id"));if(id){const [file]=await getDb().select().from(projectFiles).where(eq(projectFiles.id,id)).limit(1);if(!file)return Response.json({error:"Arquivo não encontrado."},{status:404});const object=await env.BUCKET.get(file.storageKey);if(!object)return Response.json({error:"Conteúdo do arquivo não encontrado."},{status:404});return new Response(object.body,{headers:{"Content-Type":file.contentType,"Content-Disposition":`attachment; filename*=UTF-8''${encodeURIComponent(file.name)}`}});}return Response.json({files:await getDb().select().from(projectFiles).orderBy(asc(projectFiles.createdAt))});}catch{return Response.json({error:"Não foi possível carregar os arquivos do projeto."},{status:503});}}
export async function POST(request:Request){const denied=await requirePermission("sales");if(denied)return denied;const user=await getChatGPTUser();if(!user)return Response.json({error:"Sessão não autenticada."},{status:401});try{const data=await request.formData(),saleId=Number(data.get("saleId")),file=data.get("file");if(!saleId||!(file instanceof File)||!file.size)return Response.json({error:"Selecione um arquivo válido."},{status:400});if(file.size>10*1024*1024)return Response.json({error:"O arquivo deve ter no máximo 10 MB."},{status:400});const safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-").slice(-120)||"arquivo",storageKey=`projects/${saleId}/${crypto.randomUUID()}-${safeName}`;await env.BUCKET.put(storageKey,file.stream(),{httpMetadata:{contentType:file.type||"application/octet-stream"}});const [created]=await getDb().insert(projectFiles).values({saleId,name:file.name.slice(0,180),storageKey,contentType:file.type||"application/octet-stream",size:file.size,uploadedBy:user.displayName}).returning();return Response.json({file:created},{status:201});}catch{return Response.json({error:"Não foi possível enviar o arquivo."},{status:500});}}
export async function DELETE(request:Request){const denied=await requirePermission("sales");if(denied)return denied;try{const id=Number(new URL(request.url).searchParams.get("id"));const [file]=await getDb().select().from(projectFiles).where(eq(projectFiles.id,id)).limit(1);if(!file)return Response.json({error:"Arquivo não encontrado."},{status:404});await env.BUCKET.delete(file.storageKey);await getDb().delete(projectFiles).where(eq(projectFiles.id,id));return Response.json({ok:true});}catch{return Response.json({error:"Não foi possível excluir o arquivo."},{status:500});}}
